name: CI
on: 
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 16
    - name: install modules
      run: npm install
    - name: run ESLint
      run: npm run eslint
    - name: run Prettier
      run: npm run prettier-check
    - name: Validate HTML
      run: npx html-validate --ext html ./source
    - name: Validate CSS files
      run: npm run validate-css-no-warnings
    - name: Validate JS files
      run: npm run validate-js
    - name: run JSDoc
      run: npx jsdoc -r ./source -d ./docs
    - name: run Code Quality
      run: echo "synced Code Climate to repository, check pull request to see feedback from Code Climate"
    - name: run Jest/Pupetter Tests (unit and end-to-end)
      run: npm run test
    - name: check Jest test coverage
      run: npm run test --coverage
